[colors.primary]
background = "#090516"
foreground = "#fbf4f9"

[colors.cursor]
text = "#090516"
cursor = "#fbf4f9"

[colors.vi_mode_cursor]
text = "#090516"
cursor = "#fbf4f9"

[colors.search.matches]
foreground = "#090516"
background = "#fbf4f9"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#9a7990"
background = "#fbf4f9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#090516"
red = "#8F3373"
green = "#5D2F98"
yellow = "#5943A9"
blue = "#6C4EB1"
magenta = "#A8519B"
cyan = "#935CB4"
white = "#dcadce"

[colors.bright]
black = "#9a7990"
red = "#c761a8"
green = "#905fce"
yellow = "#9484ce"
blue = "#a795d0"
magenta = "#cb94c3"
cyan = "#c1a2d4"
white = "#fbf4f9"

[colors.dim]
black = "#fbf4f9"
red = "#c761a8"
green = "#905fce"
yellow = "#9484ce"
blue = "#a795d0"
magenta = "#cb94c3"
cyan = "#c1a2d4"
white = "#9a7990"
